export PS1="\W> "
set -o vi
alias ll="ls -la"
alias vim="nvim"
alias rebuild="~/nixos/rebuild.sh"

nix-shell-generate() {
  if [ ! -f shell.nix ]; then
    cat >shell.nix <<'EOF'
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  name = "dev-shell";

  # Replace with dev tools you actually need:
  buildInputs = with pkgs; [
  ];
}
EOF
    echo "Created shell.nix in $(pwd)/shell.nix"
  fi

}
